name: edgar_planner_calendar_flutter
description: A new Flutter module project.
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_calendar:
    path: /Users/Jemis/Desktop/launchpadapps/flutter-calendar
    # git:
    #   url: https://github.com/launchpadapps-au/flutter-calendar
    #   ref: memory-machine

  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  jiffy: ^5.0.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  bloc: ^8.1.0
  pdf: ^3.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  solutelabs_lint:
    git:
      url: https://github.com/solutelabs/solutelabs_lint
      ref: dev
  intl_utils: ^2.8.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - assets/


  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/sofiapro-Regular.ttf
        - asset: assets/fonts/sofiapro-bold.ttf
          weight: 700
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  # module:
  #   androidX: true
  #   androidPackage: com.example.edgar_planner_calendar_flutter
  #   iosBundleIdentifier: com.example.edgarPlannerCalendarFlutter
flutter_intl:
  enabled: true
